name: beachu
description: Available umbrellas seeker
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 2.0.2+7
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.4.0
  url_launcher: ^6.0.6
  provider: ^6.0.0
  maps_launcher: ^2.0.0
  http: ^0.13.3
  geolocator: ^9.0.2
  modal_progress_hud_nsn: ^0.3.0
  firebase_core: ^2.8.0
  firebase_auth: ^4.3.0
  flutter_dotenv: ^5.0.0
  google_sign_in: ^6.0.2
  easy_localization: ^3.0.0
  hive: ^2.0.4
  hive_flutter: ^1.0.0
  flutter_native_splash: ^2.2.19
  sizer: ^2.0.13
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.16
  flutter_launcher_icons: ^0.12.0
  #hive_generator: ^1.1.0
  build_runner: ^2.1.4
  flutter_lints: ^2.0.1
  test_cov_console: ^0.2.2

flutter_icons:
  android: true
  ios: true
  image_path: 'assets/icon/icon.png'

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/translations/
    - .env

  fonts:
    - family: ComicNeue
      fonts:
        - asset: assets/fonts/ComicNeue-Bold.ttf
