image: node:16

stages:
  - build
  - test

build:
  script:
    - npm install
  environment: 
    - NODE_ENV=test

build:
  stage: build
  script:
    - npm install
  cache:
    paths:
      - node_modules/

test:
  stage: test
  dependencies:
    - build
  script:
    - npm test
