image: node:16

stages:
  - build
  - test

build:
  stage: build
  script:
    - npm install
    - npm install jest --global
  cache:
    paths:
      - node_modules/

test:
  stage: test
  dependencies:
    - build
  script:
    - npm test
