image: node:16

stages:
  - test

test:
  stage: test
  script:
    - cd backend/
    - npm config set -g production false
    - npm ci
    - npm install supertest --save-dev
    - npx jest --ci --runInBand --forceExit --watchAll=false
