image: node:16

stages:
  - build
  - test

build:
  stage: build
  script:
    - npm ci
    - npm i --save supertest
  cache:
    paths:
      - node_modules/

test:
  stage: test
  dependencies:
    - build
  script:
    - npx jest --ci --runInBand --forceExit --watchAll=false
