image: node:16

stages:
  - build
  - test

build:
  stage: build
  script:
    - npm install
    - npm i -g jest
  cache:
    paths:
      - node_modules/

test:
  stage: test
  dependencies:
    - build
  script:
    - npm test
