image: node:16

stages:
  - build
  - test

build:
  stage: build
  script:
    - cd backend/
    - npm config get production
    - npm config set -g production false
    - npm ci
    - npm install supertest --save-dev
    - npm install --save-dev jest
  cache:
    paths:
      - node_modules/

test:
  stage: test
  dependencies:
    - build
  script:
    - npm test
