image: node:16

stages:
  - build
  - test

build:
  script:
    - npm install

build:
  stage: build
  script:
    - npm install
  cache:
    paths:
      - node_modules/

test:
  stage: test
  dependencies:
    - npm
  script:
    - npm test
