image: node:16

stages:
  - build
  - test

build:
  stage: build
  script:
    - npm config set -g production false
    - npm ci
    - npm install supertest --save-dev
  cache:
    paths:
      - node_modules/

test:
  stage: test
  dependencies:
    - build
  script:
    - npx jest --ci --runInBand --forceExit --watchAll=false
