version: '3.1'

services:
  # MONGO-EXPRESS
  mongo-dashboard:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: 'mongodb://192.168.1.3:40001,192.168.1.3:40002,192.168.1.3:40003/beachudb?replicaSet=beachu_set'

  # REDIS DB
  redis:
    image: redis

  # BEACHU WEBSERVICE
  webservice:
    image: beachu
    env_file: .env
    environment:
      #NODE_ENV: production
      REDIS_URL: redis://redis

    ports:
      - 3000:3000
    restart: always
    deploy:
      mode: replicated
      replicas: 3
