version: '3'

services:
  mongodb1:
    image: mongo
    restart: always
    container_name: mongodb1
    environment:
      MONGO_INITDB_DATABASE: beachudb
    volumes:
      - mongodata1:/data/db
    ports:
      - '40001:27017'
    command: mongod --replSet beachu_set --bind_ip 0.0.0.0
    networks:
      - beachu-cluster

  mongodb2:
    image: mongo
    restart: always
    container_name: mongodb2
    environment:
      MONGO_INITDB_DATABASE: beachudb
    volumes:
      - mongodata2:/data/db
    ports:
      - '40002:27017'
    command: mongod --replSet beachu_set --bind_ip 0.0.0.0
    networks:
      - beachu-cluster

  mongodb3:
    image: mongo
    restart: always
    container_name: mongodb3
    environment:
      MONGO_INITDB_DATABASE: beachudb
    volumes:
      - mongodata3:/data/db
    ports:
      - '40003:27017'
    command: mongod --replSet beachu_set --bind_ip 0.0.0.0
    networks:
      - beachu-cluster

networks:
  beachu-cluster:

volumes:
  mongodata1:
  mongodata2:
  mongodata3:
